// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pczvumazsjbgdrncobvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjenZ1bWF6c2piZ2RybmNvYnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTEzNjEsImV4cCI6MjA2NzQ4NzM2MX0.j2hh_09X8RdRKFGHTPy6YJao40ALOfdZEki9Fp-JITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});